set j / 
j3
j4
j5
/ 

k / 
k9
k25
/ 

t / 
t7
t6
t9
t10
t11
t12
t13
t14
/ 

z / 
z7
z8
z10
z11
z12
z13
/ 

Parameter i(z) 
 /z7 0, 
z8 1, 
z10 2, 
z11 0, 
z12 1, 
z13 2
 /
Parameter h(k) 
 /k9 40.0
,k25 40.0
/ 

Parameter y0(k) 
 /k9 0.0
,k25 0.0
/ 

Parameter u(t) 
 /t6 5.0
,t7 5.0
,t9 5.0
,t10 5.0
,t12 5.0
,t11 5.0
,t13 5.0
,t14 5.0
/ 

Parameter f(j,k,z) 
 /j3.k9.z10 1.0, 
j3.k9.z7 0.0, 
j3.k9.z8 0.0, 
